[project]
name = "booking-service"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "psycopg2-binary",
    "pydantic",
    "pydantic-settings",
    "python-dotenv",
    "alembic",
    "httpx",
    "jinja2"
]
requires-python = ">=3.12"

[project.optional-dependencies]
dev = [
    "flake8==7.1.1",
    "pytest==8.3.4",
    "tox==4.24.1",
    "pytest-asyncio"
]

[tool.vercel]
entrypoint = "src/booking_service/main.py"