[tox]
# Додав flake8 в список автоматичного запуску
envlist = py314, flake8
skipsdist = True

[testenv]
deps = 
    pytest
    python-dotenv
    pyodbc
    pydantic
# Вказуємо шлях до модулів для тестів
setenv =
    PYTHONPATH = src
commands = pytest

[testenv:flake8]
deps =
    flake8
    flake8-bugbear
    flake8-docstrings
    flake8-typing-imports
    pep8-naming
commands =
    flake8 --ignore=B001,B036,E501,E402 src tests
exclude =
    __pycache__
    setup.py
    venv/**/.*